---

- name: Configure hasync.
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/hasync/{{ item.key }}"
    value: "{{ item.value }}"
    pretty_print: true
  loop: "{{ hasync | dict2items | default([]) }}"
...
