---

- name: Fetch xml config.
  tags:
    - always
  ansible.builtin.include_tasks:
    file: fetch.yml

- name: Configure interfaces.
  tags:
    - always
  ansible.builtin.include_tasks:
    file: interface.yml
  loop: "{{ interfaces }}"
  loop_control:
    loop_var: interface
  when: interfaces is defined

- name: Configure virtualips.
  tags:
    - always
  ansible.builtin.include_tasks:
    file: virtualip.yml
  loop: "{{ virtualips }}"
  loop_control:
    loop_var: virtualip
  when: virtualips is defined

- name: Configure dhcp.
  tags:
    - always
  ansible.builtin.include_tasks:
    file: dhcpd.yml
  loop: "{{ dhcpd }}"
  loop_control:
    loop_var: dhcpd_if
  when: dhcpd is defined

- name: Configure firewall rules.
  tags:
    - always
  ansible.builtin.include_tasks:
    file: filter.yml
  loop: "{{ filter }}"
  loop_control:
    loop_var: filter_rule
  when: filter is defined

- name: Configure nat.
  tags:
    - always
  ansible.builtin.include_tasks:
    file: nat.yml

- name: Configure hasync.
  tags:
    - always
  ansible.builtin.include_tasks:
    file: hasync.yml

- name: Copy the xml config back to the device.
  ansible.builtin.copy:
    src: "{{ local_config_path }}"
    dest: "{{ config_path }}"
    backup: true
    owner: root
    group: wheel
    mode: 0644
  register: config
  tags: copy
  notify:
    - Sync
    - Reload config

...
