---

- name: fetch
  tags:
    - always
  ansible.builtin.include_tasks:
    file: fetch.yml

- name: Configure interfaces
  tags:
    - always
  ansible.builtin.include_tasks:
    file: interface.yml
  loop: "{{ interfaces }}"
  loop_control:
    loop_var: interface
  when: interfaces is defined

- name: Configure virtualips
  tags:
    - always
  ansible.builtin.include_tasks:
    file: virtualip.yml
  loop: "{{ virtualips }}"
  loop_control:
    loop_var: virtualip
  when: virtualips is defined
      
- name: Configure dhcp
  tags:
    - always
  ansible.builtin.include_tasks:
    file: dhcpd.yml
  loop: "{{ dhcpd }}"
  loop_control:
    loop_var: dhcpd_if
  when: dhcpd is defined

- name: Configure firewall rules
  tags:
    - always
  ansible.builtin.include_tasks:
    file: filter.yml
  loop: "{{ filter }}"
  loop_control:
    loop_var: filter_rule
  when: filter is defined

- name: nat
  tags:
    - always
  ansible.builtin.include_tasks:
    file: nat.yml 

- name: hasync
  tags:
    - always
  ansible.builtin.include_tasks:
    file: hasync.yml

- name: copy
  ansible.builtin.copy:
    src: "{{ local_config_path }}"
    dest: "{{ config_path }}"
    backup: true
    owner: root
    group: wheel
    mode: 0644
  register: config
  tags: copy

- name: sync  # Sync Master to Backup
  ansible.builtin.command: "{{ item }}"
  throttle: 1
  with_items:
    - configctl filter sync
  when: config.changed
  tags:
    - sync
    - copy

- name: reload 
  ansible.builtin.command: "{{ item }}"
  throttle: 1
  with_items:
    - configctl service reload all
    - configctl webgui restart
  when: config.changed
  tags: reload
...
