---

- name: Configure nat outbound mode.
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/nat/outbound/mode"
    value: "{{ nat.outbound.mode }}"
    pretty_print: "{{ pretty_print }}"
  when: nat.outbound.mode is defined

- name: Configure nat outbound rules.
  ansible.builtin.include_tasks:
    file: nat-outbound.yml
  loop: "{{ nat.outbound.rules | default([]) }}"
  loop_control:
    loop_var: nat_outbound_rule
  when: nat.outbound.rules is defined

...
