---

- name: Configure gateways.
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/gateways/gateway_item[name/text()="{{ floating_ip_gateway.name }}"]/{{ item.key }}
    value: "{{ item.value }}"
    pretty_print: "{{ pretty_print }}"
  loop: "{{ floating_ip_gateway | dict2items }}"

...
