---

- name: interfaces - settings for an interface
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/interfaces/{{ interface.name }}/{{ item.key }}
    value: "{{ item.value }}"
    pretty_print: true
  loop: "{{ interface.settings | dict2items }}"

...
