---

- name: Fetch xml config.
  tags:
    - always
  ansible.builtin.include_tasks:
    file: fetch.yml
    apply:
      tags: fetch

- name: Configure vlans.
  tags:
    - always
  ansible.builtin.include_tasks:
    file: vlans.yml
  loop: "{{ floating_ips }}"
  loop_control:
    loop_var: floating_ip
  when: floating_ips is defined

- name: Configure vlan interfaces.
  tags:
    - always
  ansible.builtin.include_tasks:
    file: interface.yml
  loop: "{{ floating_ips }}"
  loop_control:
    loop_var: floating_ip
  when: floating_ips is defined

- name: Configure gateways.
  tags:
    - always
  ansible.builtin.include_tasks:
    file: gateways.yml
  loop: "{{ floating_ips }}"
  loop_control:
    loop_var: floating_ip
  when: floating_ips is defined

- name: Configure staticroutes.
  tags:
    - always
  ansible.builtin.include_tasks:
    file: staticroutes.yml
  loop: "{{ floating_ips }}"
  loop_control:
    loop_var: floating_ip
  when: floating_ips is defined

- name: Configure firewall rules.
  tags:
    - always
  ansible.builtin.include_tasks:
    file: filter.yml
  loop: "{{ floating_ips }}"
  loop_control:
    loop_var: floating_ip
  when: floating_ips is defined

- name: Configure ARP Proxy and Carp.
  tags:
    - always
  ansible.builtin.include_tasks:
    file: virtualip.yml
  loop: "{{ floating_ips }}"
  loop_control:
    loop_var: floating_ip
  when: floating_ips is defined

- name: Copy the xml config back to the device.
  ansible.builtin.copy:
    src: "{{ local_config_path }}"
    dest: "{{ config_path }}"
    backup: true
    owner: root
    group: wheel
    mode: "0644"
  register: config
  tags: copy
  notify:
    - Sync
    - Reload config

...
