---
# This playbook config add VM's floating Ips configuration.
# Apply only to the Master instance, as the role include a task that sync with the Backup.

- name: Configure Opnsense
  hosts: opnsenses
  roles:
    - floating-ip

- name: Configure Cisco switch
  hosts: switches
  tasks:
 
  - name: Create Vlans
    cisco.ios.ios_config:
      lines: 
      - vlan {{ item.vlan }}
      - name {{ 'Vlan_' + item.vlan }}
    loop: "{{ floating_ips }}"
    when: floating_ips is defined

  - name: Configure Untagged Interfaces
    cisco.ios.ios_l2_interfaces:
      config:
      - name: "{{ item.switch_interface }}"
        mode: access
        access:
          vlan: "{{ item.vlan }}"
      state: merged
    loop: "{{ floating_ips }}"
    when: floating_ips is defined
      
  - name: Configure tagged Interfaces
    cisco.ios.ios_config:
      lines:
      - switchport mode trunk
      - switchport trunk allowed vlan "{{ '1,1002-1005,' + (floating_ips | map(attribute='vlan') | flatten | join(',')) }}"
      parents: "{{ 'interface ' + item }}"
    loop: "{{ switch_trunk_interfaces }}"
    when: switch_trunk_interfaces is defined 

