---

# remote path of the config
config_path: /conf/config.xml

# local path for the config
local_config_path: /tmp/config-{{ inventory_hostname }}.xml


floating_ip_gateway:
  interface: "vlan{{ floating_ip.vlan }}"
  gateway: "{{ floating_ip.ip_address }}"
  name: "ip_public_{{ floating_ip.ip_address.split('.')[3] }}"
  priority: "255"
  weight: "1"
  ipprotocol: "inet"
  monitor_disable: "1"
  fargw: "1"

floating_ip_route:
  network: "{{ floating_ip.ip_address }}/32"
  gateway: "ip_public_{{ floating_ip.ip_address.split('.')[3] }}"
  disabled: "0"

floating_ip_filter:
  type: "pass"
  interface: "vlan{{ floating_ip.vlan }}"
  ipprotocol: "inet"
  statetype: "keep state"
  direction: "in"
  quick: "1"
  source/address: "{{ floating_ip.ip_address }}"
  destination/any: "1"

floating_ip_arp_proxy:
  interface: wan
  mode: proxyarp
  subnet: "{{ floating_ip.ip_address }}"
  subnet_bits: 32
  descr: "Proxy ARP {{ floating_ip.ip_address }}"
  noexpand: "0"
  nobind: "0"
  advbase: "1"
  advskew: "0"

floating_ip_vlan:
  if: "vtnet0" #device name for lan interface
  tag: "{{ floating_ip.vlan }}"
  pcp: "0"
  descr: "vlan {{ floating_ip.vlan }}"
  vlanif: "vlan0.{{ floating_ip.vlan }}"

floating_ip_vlan_interface:
  name: "vlan{{ floating_ip.vlan }}"
  settings:
    if: "vlan0.{{ floating_ip.vlan }}"
    descr: "VLAN{{ floating_ip.vlan }}"
    enable: "1"
    ipaddr: "192.168.{{ floating_ip.vlan[-2:] | int }}.{{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] | split('.') | last }}"
    subnet: "24"

virtualips:
  - vhid: 1
    settings:
      interface: wan
      mode: carp
      subnet: 192.168.102.253
      subnet_bits: 24
      descr: 'Virtual Wan IP'