---

# remote path of the config
config_path: /conf/config.xml

# local path for the config
local_config_path: /tmp/config-{{ inventory_hostname }}.xml

# whether to print the xml to output or not
pretty_print: false

opnsense_role: ''
