---

# FIXME: the opnsense sort algorithm differs ... see filter_rules_sort in src/etc/inc/filter.inc

- name: filters
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/filter/rule[descr/text()="{{ item.0.descr }}"]/{{ item.1.key }}
    value: {{ item.1.value }}"
    pretty_print: true
  with_subelements:
    - "{{ filter | default([]) }}"
    - settings

...
