---

- name: fetch
  tags:
    - always
  ansible.builtin.include_tasks:
    file: fetch.yml
    apply:
      tags: fetch

- name: interfaces
  tags:
    - always
  ansible.builtin.include_tasks:
    file: interfaces.yml
    apply:
      tags: interfaces

- name: virtualip
  tags:
    - always
  ansible.builtin.include_tasks:
    file: virtualip.yml
    apply:
      tags: virtualip
      
- name: dhcpd
  tags:
    - always
  ansible.builtin.include_tasks:
    file: dhcpd.yml
    apply:
      tags: dhcpd

- name: filter
  tags:
    - always
  ansible.builtin.include_tasks:
    file: filter.yml
    apply:
      tags: filter

- name: nat
  tags:
    - always
  ansible.builtin.include_tasks:
    file: nat.yml
    apply:
      tags: nat

- name: hasync
  tags:
    - always
  ansible.builtin.include_tasks:
    file: hasync.yml
    apply:
      tags: hasync

- name: copy
  ansible.builtin.copy:
    src: "{{ local_config_path }}"
    dest: "{{ config_path }}"
    backup: true
    owner: root
    group: wheel
    mode: 0644
  register: config
  tags: copy

- name: sync  # sync master/slave
  ansible.builtin.command: "{{ item }}"
  throttle: 1
  with_items:
    - configctl filter sync
  when:
    - config.changed 
    - inventory_hostname == groups.opnsenses.0
  tags:
    - sync
    - copy

- name: reload 
  ansible.builtin.command: "{{ item }}"
  throttle: 1
  with_items:
    - configctl service reload all
    - configctl webgui restart
  when: config.changed
  tags: reload
...
