---

- name: nat outbound - mode
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/nat/outbound/mode"
    value: "{{ nat.outbound.mode }}"
    pretty_print: true
  when: nat.outbound.mode is defined

- name: nat - rules
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/nat/outbound/rule[descr/text()="{{ item.0.descr }}"]/{{ item.1.key }}
    value: "{{ item.1.value }}"
    pretty_print: true
  with_subelements:
    - "{{ nat.outbound.rules | default([]) }}"
    - settings

...
